# Generated by Django 4.2.7 on 2026-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='interest_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de interés para cuotas', max_digits=5),
        ),
        migrations.AddField(
            model_name='promotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
