# Generated by Django 4.2.7 on 2026-09-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_promotion_interest_percent_promotion_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyConfig',
        ),
    ]
