# Generated by Django 6.1 on 2026-09-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_options_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installment_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de interés a aplicar en todas las cuotas', max_digits=5, verbose_name='Tasa de Interés para Cuotas'),
        ),
        migrations.AddField(
            model_name='product',
            name='installment_options',
            field=models.CharField(default='3,6,12', help_text='Números de cuotas separados por comas (ej: 3,6,12)', max_length=100, verbose_name='Opciones de Cuotas'),
        ),
    ]
