# Generated by Django 6.1 on 2026-09-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_installment_interest_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('document_number', models.CharField(max_length=30, unique=True, verbose_name='CI/RUC')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('payment_type', models.CharField(choices=[('CASH', 'Contado'), ('INSTALLMENTS', 'Cuotas')], default='CASH', max_length=20, verbose_name='Tipo de Pago')),
                ('installment_count', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Cuotas')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa de Interés (%)')),
                ('sale_date', models.DateField(verbose_name='Fecha de Venta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='api.customer', verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='api.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número de Cuota')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('OVERDUE', 'Atrasada')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Pagado')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='api.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['sale', 'number'],
                'unique_together': {('sale', 'number')},
            },
        ),
    ]
