# Generated by Django 6.1 on 2026-09-03 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customer_sale_installment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('customer_document', models.CharField(blank=True, max_length=30, verbose_name='CI/RUC')),
                ('customer_address', models.TextField(blank=True, verbose_name='Dirección de Entrega')),
                ('payment_type', models.CharField(choices=[('CASH', 'Contado'), ('INSTALLMENTS', 'Cuotas')], default='CASH', max_length=20, verbose_name='Forma de Pago Deseada')),
                ('installment_count', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Cuotas')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Cliente')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONTACTED', 'Contactado'), ('CONVERTED', 'Convertido en venta'), ('DISCARDED', 'Descartado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('linked_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_orders', to='api.sale', verbose_name='Venta Generada')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedido',
            },
        ),
    ]
