# Generated by Django 6.1 on 2026-09-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='business_hours',
            field=models.CharField(blank=True, help_text='Ej: Lunes a Viernes 8:00 - 18:00', max_length=200, verbose_name='Horario de Atención'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='ruc',
            field=models.CharField(blank=True, max_length=30, verbose_name='RUC'),
        ),
    ]
