# Generated by Django 4.2.7 on 2026-09-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_migrate_legacy_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('category', models.CharField(choices=[('RENT', 'Alquiler'), ('UTILITIES', 'Servicios (luz, agua, internet)'), ('SALARIES', 'Sueldos'), ('MERCHANDISE', 'Mercadería'), ('MARKETING', 'Marketing'), ('OTHER', 'Otros')], default='OTHER', max_length=20, verbose_name='Categoría')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('expense_date', models.DateField(verbose_name='Fecha')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='expenses/', verbose_name='Comprobante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
