# Generated by Django 4.2.7 on 2026-09-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de compra al proveedor, usado para calcular el gasto de mercadería al reponer stock', max_digits=10, verbose_name='Precio de Costo'),
        ),
    ]
