# Generated by Django 4.2.7 on 2026-09-05 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJUSTMENT', 'Ajuste')], max_length=12, verbose_name='Tipo')),
                ('quantity', models.IntegerField(help_text='Positivo para entradas/ajustes positivos, negativo para salidas/ajustes negativos', verbose_name='Cantidad')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('resulting_stock', models.IntegerField(verbose_name='Stock Resultante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='api.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
