# Generated by Django 4.2.7 on 2026-09-05 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Edición'), ('DELETE', 'Eliminación'), ('CUSTOM', 'Acción')], max_length=10, verbose_name='Acción')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID del Objeto')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Objeto')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Cambios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
