# Generated by Django 4.2.7 on 2026-09-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_purchaseinvoice_supplier_purchaseinvoiceitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad a partir de la cual se avisa que el stock está bajo', verbose_name='Stock Mínimo'),
        ),
    ]
