# Generated by Django 4.2.7 on 2026-09-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_min_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='economic_activity',
            field=models.CharField(blank=True, max_length=200, verbose_name='Actividad Económica'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/', verbose_name='Foto de Cédula'),
        ),
        migrations.AddField(
            model_name='customer',
            name='maps_location_url',
            field=models.URLField(blank=True, verbose_name='Ubicación (Google Maps)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference1_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referencia 1 - Nombre'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference1_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Referencia 1 - Teléfono'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference1_relation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia 1 - Relación'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference2_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referencia 2 - Nombre'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference2_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Referencia 2 - Teléfono'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference2_relation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia 2 - Relación'),
        ),
    ]
