# Generated by Django 4.2.7 on 2026-09-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_customer_economic_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('RENT', 'Alquiler'), ('UTILITIES', 'Servicios (luz, agua, internet)'), ('SALARIES', 'Sueldos'), ('MERCHANDISE', 'Mercadería'), ('MARKETING', 'Marketing'), ('MAINTENANCE', 'Mantenimiento/Reparaciones'), ('INSURANCE', 'Seguros'), ('SUPPLIES', 'Insumos de oficina/embalaje'), ('SALES_COMMISSIONS', 'Comisiones a vendedores'), ('OTHER', 'Otros')], default='OTHER', max_length=20, verbose_name='Categoría'),
        ),
    ]
