# Generated by Django 4.2.7 on 2026-09-15 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Abonado')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.installment', verbose_name='Cuota')),
            ],
            options={
                'verbose_name': 'Abono de Cuota',
                'verbose_name_plural': 'Abonos de Cuotas',
                'ordering': ['installment', 'created_at'],
            },
        ),
    ]
