# Generated by Django 4.2.7 on 2026-09-16 20:30
# Editado a mano: separa creación de SaleItem, migración de datos y borrado de
# columnas viejas en pasos ordenados, para no perder los datos de las ventas
# existentes al pasar de "un producto por venta" a "varios ítems por venta".

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


def copy_sale_data_to_items(apps, schema_editor):
    Sale = apps.get_model('api', 'Sale')
    SaleItem = apps.get_model('api', 'SaleItem')

    items = [
        SaleItem(
            sale_id=sale.pk,
            product_id=sale.product_id,
            quantity=sale.quantity,
            unit_price=sale.unit_price,
        )
        for sale in Sale.objects.all().only('id', 'product_id', 'quantity', 'unit_price')
    ]
    SaleItem.objects.bulk_create(items, batch_size=1000)


def copy_items_back_to_sale(apps, schema_editor):
    # Reversa: toma el primer item de cada venta y lo vuelca de nuevo a los
    # campos planos de Sale (best-effort, solo para poder revertir en dev).
    Sale = apps.get_model('api', 'Sale')
    SaleItem = apps.get_model('api', 'SaleItem')

    for sale in Sale.objects.all():
        item = SaleItem.objects.filter(sale_id=sale.pk).first()
        if item:
            sale.product_id = item.product_id
            sale.quantity = item.quantity
            sale.unit_price = item.unit_price
            sale.save(update_fields=['product', 'quantity', 'unit_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_purchaseinstallmentpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='api.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Ítem de Venta',
                'verbose_name_plural': 'Ítems de Venta',
            },
        ),
        migrations.RunPython(copy_sale_data_to_items, copy_items_back_to_sale),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='api.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Precio Unitario'),
        ),
    ]
