# Generated by Django 4.2.7 on 2026-09-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_saleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='unit_price',
        ),
    ]
