# Generated by Django 4.2.7 on 2026-09-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_sale_flat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Entrega Inicial'),
        ),
        migrations.AddField(
            model_name='sale',
            name='late_fee_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Interés por Mora (%)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Día de Pago Mensual'),
        ),
    ]
