# Generated by Django 4.2.7 on 2026-09-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_sale_down_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='late_fee_enabled',
            field=models.BooleanField(default=True, verbose_name='Recargo por Mora Habilitado'),
        ),
        migrations.AddField(
            model_name='installment',
            name='late_fee_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto de Mora Editado Manualmente'),
        ),
    ]
