# Generated by Django 4.2.7 on 2026-09-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_installment_late_fee_override'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['status', 'due_date'], name='api_install_status_b5960a_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date'], name='api_install_due_dat_939f57_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinstallment',
            index=models.Index(fields=['status', 'due_date'], name='api_purchas_status_447560_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinstallment',
            index=models.Index(fields=['due_date'], name='api_purchas_due_dat_8ca134_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['purchase_date'], name='api_purchas_purchas_be74cd_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='api_sale_sale_da_562c30_idx'),
        ),
    ]
