# Generated by Django 4.2.7 on 2026-09-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_installment_api_install_status_b5960a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(blank=True, max_length=50, verbose_name='N° de Nota de Crédito')),
                ('issue_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='api.purchaseinvoice', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Unitario')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.creditnote', verbose_name='Nota de Crédito')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_items', to='api.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Nota de Crédito',
                'verbose_name_plural': 'Ítems de Nota de Crédito',
            },
        ),
    ]
