# Generated by Django 4.2.7 on 2026-09-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_creditnote_creditnoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='manual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se define, la nota es un descuento sin devolución de mercadería: no afecta stock y este monto reemplaza el cálculo por ítems.', max_digits=12, null=True, verbose_name='Monto Manual'),
        ),
    ]
