# Generated by Django 4.2.7 on 2026-09-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_creditnote_manual_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='api.supplier', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='api.purchaseinvoice', verbose_name='Compra'),
        ),
        migrations.CreateModel(
            name='CreditNoteInvoiceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Asignado')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='api.creditnote', verbose_name='Nota de Crédito')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_invoice_allocations', to='api.purchaseinvoice', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Asignación de Nota de Crédito a Factura',
                'verbose_name_plural': 'Asignaciones de Nota de Crédito a Facturas',
                'unique_together': {('credit_note', 'purchase_invoice')},
            },
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='credit_note_allocations', through='api.CreditNoteInvoiceAllocation', to='api.purchaseinvoice', verbose_name='Facturas (descuento múltiple)'),
        ),
    ]
