# Generated by Django 4.2.7 on 2026-09-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_creditnote_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='is_late_fee',
            field=models.BooleanField(default=False, verbose_name='Es Recargo por Mora'),
        ),
    ]
