# Generated by Django 4.2.7 on 2026-09-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_installmentpayment_is_late_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='first_due_date',
            field=models.DateField(blank=True, help_text='Si se define, la cuota 1 vence en esta fecha exacta (en vez de un mes despues de la venta) y las siguientes se calculan a partir de ella.', null=True, verbose_name='Fecha de Vencimiento de la Primera Cuota'),
        ),
    ]
